package com.yourco.saas.domain.billing;

public enum Feature {
    EMPLOYEE_MANAGEMENT,
    TEAM_MANAGEMENT,
    PROJECT_MANAGEMENT,
    TASK_MANAGEMENT,
    CLAIMS,
    TIME_TRACKING,
    ATTENDANCE,
    LEAVE_MANAGEMENT,
    WORK_SCHEDULES,
    DOCUMENTS,
    BASIC_REPORTS,
    ADVANCED_REPORTS,
    ADVANCED_ANALYTICS,
    ADVANCED_HRM,
    CUSTOM_WORKFLOWS,
    ADVANCED_INTEGRATIONS
}
