spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5434/saas_db
    username: saas
    password: saas_dev_pw
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  data:
    redis:
      host: localhost
      port: 6380
  flyway:
    locations: classpath:db/migration/global

app:
  jwt:
    public-key: classpath:certs/jwt-public.pem
    private-key: classpath:certs/jwt-private.pem
    access-token-ttl: 15m
    refresh-token-ttl: 7d

server:
  port: 8090