spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5434/saas_db
    username: saas
    password: saas_dev_pw
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  data:
    redis:
      host: localhost
      port: 6380
  flyway:
    locations: classpath:db/migration/global

server:
  port: 8090