spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/saas_db
    username: saas
    password: saas_dev_pw
  jpa:
    hibernate:
      ddl-auto: none
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8081